# BZip2
# https://cmake.org/cmake/help/latest/module/FindBZip2.html
#
#   find_package(BZip2 REQUIRED)
#   target_link_libraries(main PRIVATE BZip2::BZip2)
#
cmake_policy(PUSH)
cmake_policy(VERSION 3.20)
set(CMAKE_IMPORT_FILE_VERSION 1)

set(BZIP2_VERSION_STRING ${BZip2_VERSION})
set(BZIP2_VERSION ${BZIP2_VERSION_STRING})
set(BZIP2_INCLUDE_DIRS)

set(BZIP2_LIBRARIES BZip2::BZip2)

include(AceImportLibrary)
ace_import_library(BZip2::BZip2 C NAMES bz2 HEADERS bzlib.h
  COMPILE_DEFINITIONS_SHARED BZ_IMPORT)

string(REPLACE "." ";" BZIP2_VERSION_LIST ${BZIP2_VERSION})
list(GET BZIP2_VERSION_LIST 0 BZIP2_VERSION_MAJOR)
list(GET BZIP2_VERSION_LIST 1 BZIP2_VERSION_MINOR)
list(GET BZIP2_VERSION_LIST 2 BZIP2_VERSION_PATCH)
set(BZIP2_VERSION_TWEAK 0)

set(BZIP2_NEED_PREFIX ON)

set(BZIP2_INCLUDE_DIR "${BZIP2_INCLUDE_DIRS}" CACHE STRING "")
set(BZIP2_LIBRARY "${BZIP2_LIBRARIES}" CACHE STRING "")
set(BZIP2_FOUND 1)

set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
