# Settings
# x86-64: CMOV, CMPXCHG8B, FPU, FXSR, MMX, FXSR, SCE, SSE, SSE2
# x86-64-v2: (close to Nehalem) CMPXCHG16B, LAHF-SAHF, POPCNT, SSE3, SSE4.1, SSE4.2, SSSE3
# x86-64-v3: (close to Haswell) AVX, AVX2, BMI1, BMI2, F16C, FMA, LZCNT, MOVBE, XSAVE
# x86-64-v4: AVX512F, AVX512BW, AVX512CD, AVX512DQ, AVX512VL

set(ARCH x86-64-v3)
set(LLVM ${CMAKE_CURRENT_LIST_DIR}/llvm)
set(MSVC ${CMAKE_CURRENT_LIST_DIR}/msvc)
set(CMAKE_MSVC_RUNTIME_LIBRARY "" CACHE STRING "")
set(CMAKE_CONFIGURATION_TYPES Debug Release MinSizeRel RelWithDebInfo CACHE STRING "" FORCE)
set_property(GLOBAL PROPERTY DEBUG_CONFIGURATIONS Debug MinSizeRel RelWithDebInfo)

# Tools
find_program(CMAKE_C_COMPILER clang PATHS ${LLVM}/bin REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_CXX_COMPILER clang++ PATHS ${LLVM}/bin REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_LINKER lld-link PATHS ${LLVM}/bin REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_AR llvm-ar PATHS ${LLVM}/bin REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_NM llvm-nm PATHS ${LLVM}/bin REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_RANLIB llvm-ranlib PATHS ${LLVM}/bin REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_RC_COMPILER llvm-rc PATHS ${LLVM}/bin REQUIRED NO_DEFAULT_PATH)

find_program(CCACHE ccache)
if(CCACHE)
  set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE} CACHE PATH "")
  set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE} CACHE PATH "")
endif()
unset(CCACHE)

# System
set(CMAKE_CROSSCOMPILING ON CACHE BOOL "")
set(CMAKE_SYSTEM_NAME Windows CACHE STRING "")
set(CMAKE_SYSTEM_VERSION 10.0 CACHE STRING "")
set(CMAKE_SYSTEM_PROCESSOR AMD64 CACHE STRING "")

# C Compiler
set(CMAKE_C_STANDARD 11 CACHE STRING "")
set(CMAKE_C_EXTENSIONS OFF CACHE BOOL "")
set(CMAKE_C_STANDARD_REQUIRED ON CACHE BOOL "")
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc CACHE STRING "")
set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES ${LLVM}/lib/clang/12.0.0/include ${MSVC}/include CACHE PATH "")

# C++ Compiler
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")
set(CMAKE_CXX_STANDARD 20 CACHE STRING "")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc CACHE STRING "")
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${LLVM}/lib/clang/12.0.0/include ${MSVC}/include CACHE PATH "")

# Compiler Flags
set(FLAGS "-march=${ARCH} -nostdinc -ffast-math -fmerge-all-constants")
set(FLAGS "${FLAGS} -fdiagnostics-absolute-paths -fcolor-diagnostics")
set(FLAGS "${FLAGS} -fms-compatibility-version=19.28 -Wno-language-extension-token")
set(FLAGS "${FLAGS} -DWIN32 -D_WINDOWS -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -D_CRT_USE_BUILTIN_OFFSETOF=1")

set(FLAGS_MD "-D_MT -D_DLL -Xclang --dependent-lib=msvcrt")
set(FLAGS_MT "-D_MT -Xclang --dependent-lib=libcmt -Xclang -flto-visibility-public-std")

set(CMAKE_C_FLAGS ${FLAGS} CACHE STRING "")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g -Xclang -gcodeview ${FLAGS_MD}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG ${FLAGS_MT} -flto=full" CACHE STRING "")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG ${FLAGS_MD}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g -Xclang -gcodeview -DNDEBUG ${FLAGS_MD}" CACHE STRING "")

set(FLAGS "${FLAGS} -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -D_HAS_EXCEPTIONS=0")
set(FLAGS "${FLAGS} -fno-rtti -D_HAS_STATIC_RTTI=0")

set(CMAKE_CXX_FLAGS ${FLAGS} CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g -Xclang -gcodeview ${FLAGS_MD}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG ${FLAGS_MT} -flto=full -fwhole-program-vtables" CACHE STRING "")
set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG ${FLAGS_MD}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -Xclang -gcodeview -DNDEBUG ${FLAGS_MD}" CACHE STRING "")

foreach(LANG C CXX)
  set(CMAKE_${LANG}_STANDARD_LIBRARIES "-lkernel32 -luser32 -lshell32 -lgdi32" CACHE STRING "")
endforeach()

unset(FLAGS_MT)
unset(FLAGS_MD)
unset(FLAGS)

# Definitions
add_compile_definitions(_ATL_SECURE_NO_DEPRECATE _SCL_SECURE_NO_WARNINGS)
add_compile_definitions(_CRT_SECURE_NO_DEPRECATE _CRT_SECURE_NO_WARNINGS)
add_compile_definitions(_CRT_NONSTDC_NO_DEPRECATE)

# Linker Flags
foreach(LINKER SHARED MODULE EXE)
  set(CMAKE_${LINKER}_LINKER_FLAGS "-L${MSVC}/lib -Wno-unused-command-line-argument" CACHE STRING "")
  set(CMAKE_${LINKER}_LINKER_FLAGS_DEBUG "-Wl,/DEBUG -Wl,/INCREMENTAL" CACHE STRING "")
  set(CMAKE_${LINKER}_LINKER_FLAGS_RELEASE "-Wl,/OPT:REF -Wl,/OPT:ICF -Wl,/INCREMENTAL:NO" CACHE STRING "")
  set(CMAKE_${LINKER}_LINKER_FLAGS_MINSIZEREL "-Wl,/OPT:REF -Wl,/OPT:ICF -Wl,/INCREMENTAL:NO" CACHE STRING "")
  set(CMAKE_${LINKER}_LINKER_FLAGS_RELWITHDEBINFO "-Wl,/DEBUG -Wl,/INCREMENTAL" CACHE STRING "")
endforeach()

# RC Compiler
set(CMAKE_RC_STANDARD_INCLUDE_DIRECTORIES ${LLVM}/lib/clang/12.0.0/include ${MSVC}/include CACHE PATH "")

# CMake Directories
set(CMAKE_FIND_ROOT_PATH ${MSVC} CACHE PATH "")
set(CMAKE_SYSTEM_LIBRARY_PATH ${MSVC}/lib CACHE PATH "")
set(CMAKE_SYSTEM_INCLUDE_PATH ${MSVC}/include CACHE PATH "")

unset(MSVC)
unset(LLVM)
unset(ARCH)
