#!/bin/sh
set -e
SRC=$(readlink -f -- "${0}" || realpath -- "${0}")
RES=$(dirname "${SRC}")
ACE=$(dirname "${RES}")
cd "${ACE}" || exit 1

PORTS=$(echo doctest[core] lua[core,cpp] \
  zlib[core] bzip2[core] liblzma[core] lz4[core] brotli[core] zstd[core] libdeflate[core,decompression,gzip,zlib] \
  libjpeg-turbo[core] libpng[core] imath[core] openexr[core] libyuv[core] aom[core] libavif[core,aom] draco[core] \
  freetype[core,zlib,bzip2,brotli,png,subpixel-rendering] harfbuzz[core,freetype] \
  spirv-headers[core] spirv-tools[core] glslang[core,opt] shaderc[core] volk[core] \
  vulkan-headers[core] vulkan-utility-libraries[core] vulkan-memory-allocator[core] \
  convectionkernels[core] meshoptimizer[core] recastnavigation[core] polyclipping[core] \
  simdjson[core,deprecated,threads,utf8-validation] fastgltf[core] ktx[core,vulkan] \
  lunasvg[core] plutovg[core] plutosvg[core] itlib[core] robin-hood-hashing[core] \
  rmlui[core,freetype,svg] glm[core] sdl3[core])

res/vcpkg install --triplet=linux --recurse ${PORTS} liburing[core]
res/vcpkg install --triplet=mingw --recurse ${PORTS}

if [ ! -f vcpkg/installed/linux/include/lua.hpp ] || [ ! -f vcpkg/installed/mingw/include/lua.hpp ]; then
  find vcpkg/buildtrees/lua/src -name lua.hpp -print -quit | while read file; do
    cp -a "${file}" vcpkg/installed/linux/include/
    cp -a "${file}" vcpkg/installed/mingw/include/
  done
fi
