set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_CMAKE_SYSTEM_VERSION 10.0)
set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled)
set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../toolchain.cmake")

if(PORT STREQUAL "harfbuzz")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_LINKER=")
endif()

if(PORT STREQUAL "pugixml")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DPUGIXML_NO_EXCEPTIONS=ON")
endif()

if(PORT STREQUAL "libpng")
  set(VCPKG_C_FLAGS "-D_WIN32")
endif()

if(PORT STREQUAL "rmlui")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DRMLUI_CUSTOM_RTTI=ON")
endif()

if(PORT STREQUAL "lua")
  set(VCPKG_C_FLAGS "-DLUA_USE_LONGJMP")
endif()

if(DEFINED VCPKG_C_FLAGS AND NOT DEFINED VCPKG_CXX_FLAGS)
  set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")
endif()

set(CMAKE_SYSTEM_PROGRAM_PATH "${CMAKE_CURRENT_LIST_DIR}/../../bin")
