include("${CMAKE_CURRENT_LIST_DIR}/brotli-config-targets.cmake")
foreach(target IN ITEMS brotlicommon brotlidec brotlienc)
  if(TARGET brotli::${target} AND NOT TARGET brotli::${target}-static)
    _add_library(brotli::${target}-static INTERFACE IMPORTED)
    set_target_properties(brotli::${target}-static PROPERTIES INTERFACE_LINK_LIBRARIES "brotli::${target}")
  endif()
  if(NOT TARGET brotli::${target} AND TARGET brotli::${target}-static)
    _add_library(brotli::${target} INTERFACE IMPORTED)
    set_target_properties(brotli::${target} PROPERTIES INTERFACE_LINK_LIBRARIES "brotli::${target}-static")
  endif()
endforeach()
