set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CMAKE_SYSTEM_VERSION 5.10.0)
set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_BUILD_TYPE release)
set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled)
set(X_VCPKG_FORCE_VCPKG_WAYLAND_LIBRARIES ON)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../linux.cmake")
set(VCPKG_FIXUP_ELF_RPATH ON)

if(PORT STREQUAL "zlib")
  set(VCPKG_C_FLAGS "-DNO_GETENV -DNO_PUTENV -D_LARGEFILE64_SOURCE")
endif()

if(PORT STREQUAL "lua")
  set(VCPKG_C_FLAGS "-DLUA_USE_LONGJMP")
endif()

if(PORT STREQUAL "luajit")
  set(VCPKG_LINKER_FLAGS "-ldl -lunwind")
endif()

if(DEFINED VCPKG_C_FLAGS AND NOT DEFINED VCPKG_CXX_FLAGS)
  set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")
endif()

set(CMAKE_SYSTEM_PROGRAM_PATH "${CMAKE_CURRENT_LIST_DIR}/../../bin")
