set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
set(ACE_MAIN "main${VCPKG_TARGET_EXECUTABLE_SUFFIX}")
set(ACE_MAIN "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${ACE_MAIN}")

if(CMAKE_HOST_UNIX AND VCPKG_TARGET_IS_WINDOWS)
  find_program(WINE wine PATHS ${CMAKE_SYSTEM_PROGRAM_PATH} REQUIRED)
  get_filename_component(WINEPATH "bin" REALPATH BASE_DIR
    "${CURRENT_INSTALLED_DIR}/../../../sys/mingw")
  set(ACE_MAIN "${CMAKE_COMMAND};-E;env;WINEPATH=${WINEPATH};${WINE};${ACE_MAIN}")
endif()

vcpkg_cmake_configure(SOURCE_PATH ${CMAKE_CURRENT_LIST_DIR})
vcpkg_cmake_build()

execute_process(COMMAND ${ACE_MAIN}
  WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
  COMMAND_ERROR_IS_FATAL ANY COMMAND_ECHO STDOUT)
