# FLAC
#
#   find_package(FLAC REQUIRED)
#   target_link_libraries(main PRIVATE FLAC::FLAC FLAC::FLAC++)
#
cmake_policy(PUSH)
cmake_policy(VERSION 3.20)
set(CMAKE_IMPORT_FILE_VERSION 1)

set(FLAC_VERSION_STRING ${FLAC_VERSION})
set(FLAC_VERSION ${FLAC_VERSION_STRING})
set(FLAC_INCLUDE_DIRS)

set(FLAC_LIBRARIES FLAC::FLAC)

include(CMakeFindDependencyMacro)
find_dependency(Ogg REQUIRED)

include(AceImportLibrary)
ace_import_library(FLAC::FLAC C NAMES flac HEADERS FLAC/all.h
  LINK_LIBRARIES Ogg::ogg COMPILE_DEFINITIONS_STATIC FLAC__NO_DLL)

ace_import_library(FLAC::FLAC++ CXX NAMES flac++ HEADERS FLAC++/all.h
  LINK_LIBRARIES FLAC::FLAC)

string(REPLACE "." ";" FLAC_VERSION_LIST ${FLAC_VERSION})
list(GET FLAC_VERSION_LIST 0 FLAC_VERSION_MAJOR)
list(GET FLAC_VERSION_LIST 1 FLAC_VERSION_MINOR)
list(GET FLAC_VERSION_LIST 2 FLAC_VERSION_PATCH)
set(FLAC_VERSION_TWEAK 0)

set(FLAC_INCLUDE_DIR "${FLAC_INCLUDE_DIRS}" CACHE STRING "")
set(FLAC_LIBRARY "${FLAC_LIBRARIES}" CACHE STRING "")
set(FLAC_FOUND 1)

set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
