set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CMAKE_SYSTEM_VERSION 5.10.0)
set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled)
set(X_VCPKG_FORCE_VCPKG_WAYLAND_LIBRARIES ON)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../toolchain.cmake")
set(VCPKG_FIXUP_ELF_RPATH ON)

if(PORT STREQUAL "zlib")
  set(VCPKG_C_FLAGS "-DNO_GETENV -DNO_PUTENV -D_LARGEFILE64_SOURCE")
endif()

if(PORT STREQUAL "bzip2")
  set(VCPKG_C_FLAGS "-D_POSIX_C_SOURCE=200809L")
endif()

if(PORT STREQUAL "pugixml")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DPUGIXML_NO_EXCEPTIONS=ON")
endif()

if(PORT STREQUAL "libjpeg-turbo")
  set(VCPKG_C_FLAGS "-D_GNU_SOURCE")
endif()

if(PORT STREQUAL "rmlui")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DRMLUI_CUSTOM_RTTI=ON")
endif()

if(PORT STREQUAL "lua")
  set(VCPKG_C_FLAGS "-DLUA_USE_LONGJMP")
endif()

if(DEFINED VCPKG_C_FLAGS AND NOT DEFINED VCPKG_CXX_FLAGS)
  set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")
endif()

set(CMAKE_SYSTEM_PROGRAM_PATH "${CMAKE_CURRENT_LIST_DIR}/../../bin")
