set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_CMAKE_SYSTEM_VERSION 10.0)
set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled)
set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)

if(PORT STREQUAL "zlib")
  set(VCPKG_C_FLAGS "-DNO_GETENV -DNO_PUTENV -D_LARGEFILE64_SOURCE")
endif()

if(PORT STREQUAL "harfbuzz")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_LINKER=)
endif()

if(PORT STREQUAL "libpng")
  set(VCPKG_C_FLAGS "-D_WIN32")
endif()

if(PORT STREQUAL "ktx")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DACE_DISABLE_AVX=ON)
endif()

if(PORT STREQUAL "glm")
  list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DGLM_ENABLE_CXX_20=ON)
  list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DGLM_ENABLE_SIMD_AVX2=ON)
endif()

if(DEFINED VCPKG_C_FLAGS AND NOT DEFINED VCPKG_CXX_FLAGS)
  set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")
endif()

file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/../.." ACE)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${ACE}/res/toolchain.cmake")
set(CMAKE_SYSTEM_PROGRAM_PATH "${ACE}/bin")
set(CLANG "${ACE}/bin/clang.exe")
set(NINJA "${ACE}/bin/ninja.exe")
set(YASM "${ACE}/bin/yasm.exe")
