set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=20")

if(PORT STREQUAL "bzip2" AND VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
  list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_C_EXTENSIONS=ON")
endif()

if(PORT STREQUAL "libpng" AND NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
  list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_C_FLAGS=-D_WIN32")
endif()

if(PORT STREQUAL "harfbuzz")
  list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_LINKER=")
endif()

if(PORT STREQUAL "libjpeg-turbo")
  set(VCPKG_C_FLAGS "-DNO_GETENV -DNO_PUTENV")
  set(VCPKG_CXX_FLAGS "-DNO_GETENV -DNO_PUTENV")
  if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -D_DEFAULT_SOURCE")
    set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -D_DEFAULT_SOURCE")
  endif()
endif()
