# Toolchain
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
string(SUBSTRING "${VCPKG_TARGET_TRIPLET}" 0 5 ACE_SYSTEM_NAME)
string(SUBSTRING "${VCPKG_TARGET_TRIPLET}" 6 -1 ACE_SYSTEM_ARCH)
include(${CMAKE_CURRENT_LIST_DIR}/toolchain.cmake)
unset(ACE_SYSTEM_ARCH)
unset(ACE_SYSTEM_NAME)

# Search Paths
#set(CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH}
#  ${ACE}/build/vcpkg/installed/${ACE_SYSTEM_NAME}-${ACE_SYSTEM_ARCH}
#  CACHE PATH "" FORCE)

# Compiler Flags
set(CMAKE_C_FLAGS_INIT
 "${CMAKE_C_FLAGS_INIT} ${VCPKG_C_FLAGS}")
set(CMAKE_C_FLAGS_DEBUG_INIT
 "${CMAKE_C_FLAGS_DEBUG_INIT} ${VCPKG_C_FLAGS_DEBUG}")
set(CMAKE_C_FLAGS_RELEASE_INIT
 "${CMAKE_C_FLAGS_RELEASE_INIT} ${VCPKG_C_FLAGS_RELEASE}")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT
 "${CMAKE_C_FLAGS_MINSIZEREL_INIT} ${VCPKG_C_FLAGS_RELEASE}")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT
 "${CMAKE_C_FLAGS_RELWITHDEBINFO_INIT} ${VCPKG_C_FLAGS_DEBUG}")

set(CMAKE_CXX_FLAGS_INIT
 "${CMAKE_CXX_FLAGS_INIT} ${VCPKG_CXX_FLAGS}")
set(CMAKE_CXX_FLAGS_DEBUG_INIT
 "${CMAKE_CXX_FLAGS_DEBUG_INIT} ${VCPKG_CXX_FLAGS_DEBUG}")
set(CMAKE_CXX_FLAGS_RELEASE_INIT
 "${CMAKE_CXX_FLAGS_RELEASE_INIT} ${VCPKG_CXX_FLAGS_RELEASE}")
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT
 "${CMAKE_CXX_FLAGS_MINSIZEREL_INIT} ${VCPKG_CXX_FLAGS_RELEASE}")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT
 "${CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT} ${VCPKG_CXX_FLAGS_DEBUG}")

# Linker Flags
foreach(LINKER SHARED MODULE EXE)
  set(CMAKE_${LINKER}_LINKER_FLAGS_INIT
   "${CMAKE_${LINKER}_LINKER_FLAGS_INIT} ${VCPKG_LINKER_FLAGS}")
  set(CMAKE_${LINKER}_LINKER_FLAGS_DEBUG_INIT
   "${CMAKE_${LINKER}_LINKER_FLAGS_DEBUG_INIT} ${VCPKG_LINKER_FLAGS_DEBUG}")
  set(CMAKE_${LINKER}_LINKER_FLAGS_RELEASE_INIT
   "${CMAKE_${LINKER}_LINKER_FLAGS_RELEASE_INIT} ${VCPKG_LINKER_FLAGS_RELEASE}")
  set(CMAKE_${LINKER}_LINKER_FLAGS_MINSIZEREL_INIT
   "${CMAKE_${LINKER}_LINKER_FLAGS_MINSIZEREL_INIT} ${VCPKG_LINKER_FLAGS_RELEASE}")
  set(CMAKE_${LINKER}_LINKER_FLAGS_RELWITHDEBINFO_INIT
   "${CMAKE_${LINKER}_LINKER_FLAGS_RELWITHDEBINFO_INIT} ${VCPKG_LINKER_FLAGS_DEBUG}")
endforeach()

# Platform Variables
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
  ${CMAKE_TRY_COMPILE_PLATFORM_VARIABLES}
  VCPKG_CHAINLOAD_TOOLCHAIN_FILE
  VCPKG_LIBRARY_LINKAGE
  CACHE STRING "" FORCE)
