#!/bin/sh
set -e
export LC_ALL=C
SCRIPT=$(readlink -f -- "${0}" || realpath -- "${0}")
SRC=$(dirname "${SCRIPT}")
ACE=$(dirname "${SRC}")

VCPKG_DISABLE_METRICS=1 \
VCPKG_FORCE_SYSTEM_BINARIES=1 \
VCPKG_WORKS_SYSTEM_BINARIES=1 \
VCPKG_ROOT="${ACE}/vcpkg" \
"${ACE}/vcpkg/vcpkg" \
  --overlay-ports=${ACE}/res/ports \
  --overlay-triplets=${ACE}/res/triplets \
  --x-install-root=${ACE}/sys/linux/ports \
  --feature-flags=-binarycaching \
  --host-triplet=linux \
  --triplet=linux $@
